use adlister_db;
INSERT INTO categories (name) VALUES ('Abstract Strategy');
INSERT INTO categories (name) VALUES ('Action / Dexterity');
INSERT INTO categories (name) VALUES ('Adventure');
INSERT INTO categories (name) VALUES ('Age of Reason');
INSERT INTO categories (name) VALUES ('American Civil War');
INSERT INTO categories (name) VALUES ('American Indian Wars');
INSERT INTO categories (name) VALUES ('American Revolutionary War');
INSERT INTO categories (name) VALUES ('American West');
INSERT INTO categories (name) VALUES ('Ancient');
INSERT INTO categories (name) VALUES ('Animals');
INSERT INTO categories (name) VALUES ('Arabian');
INSERT INTO categories (name) VALUES ('Aviation/Flight');
INSERT INTO categories (name) VALUES ('Bluffing');
INSERT INTO categories (name) VALUES ('Book');
INSERT INTO categories (name) VALUES ('Card Game');
INSERT INTO categories (name) VALUES ('Children''s Game');
INSERT INTO categories (name) VALUES ('City Building');
INSERT INTO categories (name) VALUES ('Civil War');
INSERT INTO categories (name) VALUES ('Civilization');
INSERT INTO categories (name) VALUES ('Collectible Components');
INSERT INTO categories (name) VALUES ('Comic Book/Strip');
INSERT INTO categories (name) VALUES ('Deduction');
INSERT INTO categories (name) VALUES ('Dice');
INSERT INTO categories (name) VALUES ('Economic');
INSERT INTO categories (name) VALUES ('Educational');
INSERT INTO categories (name) VALUES ('Electronic');
INSERT INTO categories (name) VALUES ('Environmental');
INSERT INTO categories (name) VALUES ('Expansion for Base-game');
INSERT INTO categories (name) VALUES ('Exploration');
INSERT INTO categories (name) VALUES ('Fan Expansion');
INSERT INTO categories (name) VALUES ('Fantasy');
INSERT INTO categories (name) VALUES ('Farming');
INSERT INTO categories (name) VALUES ('Fighting');
INSERT INTO categories (name) VALUES ('Game System');
INSERT INTO categories (name) VALUES ('Horror');
INSERT INTO categories (name) VALUES ('Humor');
INSERT INTO categories (name) VALUES ('Industry/Manufacturing');
INSERT INTO categories (name) VALUES ('Korean War');
INSERT INTO categories (name) VALUES ('Mafia');
INSERT INTO categories (name) VALUES ('Math');
INSERT INTO categories (name) VALUES ('Mature/Adult');
INSERT INTO categories (name) VALUES ('Maze');
INSERT INTO categories (name) VALUES ('Medical');
INSERT INTO categories (name) VALUES ('Medieval');
INSERT INTO categories (name) VALUES ('Memory');
INSERT INTO categories (name) VALUES ('Miniatures');
INSERT INTO categories (name) VALUES ('Modern Warfare');
INSERT INTO categories (name) VALUES ('Movies/TV/Radio');
INSERT INTO categories (name) VALUES ('Murder/Mystery');
INSERT INTO categories (name) VALUES ('Music');
INSERT INTO categories (name) VALUES ('Mythology');
INSERT INTO categories (name) VALUES ('Napoleonic');
INSERT INTO categories (name) VALUES ('Nautical');
INSERT INTO categories (name) VALUES ('Negotiation');
INSERT INTO categories (name) VALUES ('Novel-based');
INSERT INTO categories (name) VALUES ('Number');
INSERT INTO categories (name) VALUES ('Party Game');
INSERT INTO categories (name) VALUES ('Pike and Shot');
INSERT INTO categories (name) VALUES ('Pirates');
INSERT INTO categories (name) VALUES ('Political');
INSERT INTO categories (name) VALUES ('Post-Napoleonic');
INSERT INTO categories (name) VALUES ('Prehistoric');
INSERT INTO categories (name) VALUES ('Print & Play');
INSERT INTO categories (name) VALUES ('Puzzle');
INSERT INTO categories (name) VALUES ('Racing');
INSERT INTO categories (name) VALUES ('Real-time');
INSERT INTO categories (name) VALUES ('Religious');
INSERT INTO categories (name) VALUES ('Renaissance');
INSERT INTO categories (name) VALUES ('Science Fiction');
INSERT INTO categories (name) VALUES ('Space Exploration');
INSERT INTO categories (name) VALUES ('Spies/Secret Agents');
INSERT INTO categories (name) VALUES ('Sports');
INSERT INTO categories (name) VALUES ('Territory Building');
INSERT INTO categories (name) VALUES ('Trains');
INSERT INTO categories (name) VALUES ('Transportation');
INSERT INTO categories (name) VALUES ('Travel');
INSERT INTO categories (name) VALUES ('Trivia');
INSERT INTO categories (name) VALUES ('Video Game theme');
INSERT INTO categories (name) VALUES ('Vietnam War');
INSERT INTO categories (name) VALUES ('Wargame');
INSERT INTO categories (name) VALUES ('Word Game');
INSERT INTO categories (name) VALUES ('World War I');
INSERT INTO categories (name) VALUES ('World War II');
INSERT INTO categories (name) VALUES ('Zombies');